accounts/urls.py
from django.urls import path
from accounts.views import user, department, subject, user_profile

app_name = 'accounts'

urlpatterns = [
    # 用户管理
    path('user/list/', user.user_list, name='user_list'),
    path('user/add/', user.user_add, name='user_add'),
    path('user/delete/', user.user_delete, name='user_delete'),
    path('user/<int:nid>/edit/', user.user_edit, name='user_edit'),
    path('user/import/', user.import_users, name='import_users'),
    path('user/<int:nid>/reset/', user.user_reset, name='user_reset'),
    
    # 部门管理
    path('department/list/', department.department_list, name='department_list'),
    path('department/add/', department.department_add, name='department_add'),
    path('department/delete/', department.department_delete, name='department_delete'),
    path('department/<int:nid>/edit/', department.department_edit, name='department_edit'),
    path('department/multi/', department.department_multi, name='department_multi'),

    # 学科管理
    path('subject/list/', subject.subject_list, name='subject_list'),
    path('subject/add/', subject.subject_add, name='subject_add'),
    path('subject/delete/', subject.subject_delete, name='subject_delete'),
    path('subject/edit/', subject.subject_edit, name='subject_edit'),
    path('subject/detail/', subject.subject_detail, name='subject_detail'),
    path('subject/multi/', subject.subject_multi, name='subject_multi'), 
    
    # 个人用户
    path('profile/', user_profile.user_profile, name='user_profile'),
    path('change_password/', user_profile.change_password, name='change_password'),
    path('update_avatar/', user_profile.update_avatar, name='update_avatar'), 
    path('userprofile/edit/', user_profile.user_edit_profile, name='user_edit_profile'),

]

teacher_system/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import account
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # 首页
    path('', account.index, name='index'),
    
    # 后台管理
    path('admin/', admin.site.urls),
    
    # 登录注销
    path('image/code/', account.image_code, name='image_code'),
    path("login/", account.user_login, name="login"),
    path("logout/", account.user_logout, name="logout"),
    
    # 路由分发
    path('accounts/', include('accounts.urls')),
    path('assessments/', include('assessments.urls')),
    path('certificate/', include('certificate.urls')),
    
]

# 仅在开发环境中添加此配置,生产环境由Nginx处理
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import AbstractUser
import datetime
import os

# Create your models here.

class Department(models.Model):
    """年级（部门）"""
    title = models.CharField(max_length=100, verbose_name="年级（部门）")

    def __str__(self):
        return self.title


class Subject(models.Model):
    """任教学科"""
    title = models.CharField(max_length=100, verbose_name="学科")

    def __str__(self):
        return self.title


class UserInfo(AbstractUser):
    # 头像
    avatar = models.ImageField(upload_to='avatar/%Y/%m/%d', null=True, blank=True, verbose_name="头像")
    name = models.CharField(max_length=100, verbose_name="姓名")
    birthday = models.DateField(null=True, blank=True, verbose_name="出生日期")
    # 参加工作时间
    work_time = models.DateField(verbose_name="参加工作时间", blank=True, null=True)
    # 入党时间
    party_time = models.DateField(verbose_name="入党时间", blank=True, null=True)
    idnumber = models.CharField(
        max_length=18, verbose_name="身份证号", blank=True, null=True)
    gender_choices = (
        (1, '男'),
        (2, '女'),
    )
    gender = models.SmallIntegerField(
        verbose_name='性别', choices=gender_choices, blank=True, null=True)
    phone = models.CharField(max_length=11, verbose_name="电话")
    department = models.ForeignKey(
        Department, on_delete=models.SET_NULL, null=True, verbose_name="所属年级（部门）")
    subject = models.ForeignKey(
        Subject, on_delete=models.SET_NULL, null=True, verbose_name="任教学科")    
    
    # 民族
    nation = models.CharField(verbose_name="民族", max_length=100, blank=True, null=True)
    # 政治面貌
    political_status = models.CharField(verbose_name="政治面貌", max_length=100, blank=True, null=True)
    # 籍贯
    native_place = models.CharField(verbose_name="籍贯", max_length=100, blank=True, null=True)
    # 现住址
    address = models.CharField(verbose_name="现住址", max_length=100, blank=True, null=True)
        
    # 第一学历
    first_education = models.CharField(verbose_name="第一学历", max_length=100, blank=True, null=True)
    # 第一学历毕业院校
    first_education_school = models.CharField(verbose_name="第一学历毕业院校", max_length=100, blank=True, null=True)
    # 第一学历专业
    first_education_major = models.CharField(verbose_name="第一学历专业", max_length=100, blank=True, null=True)
    # 第一学历毕业时间
    first_education_time = models.DateField(verbose_name="第一学历毕业时间", blank=True, null=True)
    # 最高学历
    highest_education = models.CharField(verbose_name="最高学历", max_length=100, blank=True, null=True)
    # 最高学历毕业院校
    highest_education_school = models.CharField(verbose_name="最高学历毕业院校", max_length=100, blank=True, null=True)
    # 最高学历专业
    highest_education_major = models.CharField(verbose_name="最高学历专业", max_length=100, blank=True, null=True)
    # 最高学历毕业时间
    highest_education_time = models.DateField(verbose_name="最高学历毕业时间", blank=True, null=True)
    
    # 专业资格
    professional_qualification = models.CharField(verbose_name="专业资格", max_length=100, blank=True, null=True)
    professional_qualification_time = models.DateField(verbose_name="专业资格取得时间", blank=True, null=True)
    # 职称及聘任时间
    professional_title = models.CharField(verbose_name="聘任职称", max_length=100, blank=True, null=True)
    professional_title_time = models.DateField(verbose_name="聘任时间", blank=True, null=True)        
    # 分级竞聘后聘任等级及时间
    appointment_grade = models.CharField(verbose_name="分级竞聘后聘任等级", max_length=100, blank=True, null=True)
    appointment_grade_time = models.DateField(verbose_name="分级竞聘后聘任时间", blank=True, null=True)
    # 调入我校时间
    transfer_time = models.DateField(verbose_name="调入我校时间", blank=True, null=True)
    
    # 保存方法可以简化，使用更健壮的路径处理
    def save(self, *args, **kwargs):
        # 确保上传时目录存在
        if self.avatar:
            # 获取完整上传路径（不含文件名）
            upload_dir = os.path.dirname(os.path.join(settings.MEDIA_ROOT, self.avatar.name))
            os.makedirs(upload_dir, exist_ok=True)
        super().save(*args, **kwargs)

accounts/views.py
from django.shortcuts import render

# Create your views here.

accounts/views/account.py
from io import BytesIO
from django import forms
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from utils.bootstrap import BootStrapForm
from utils.code import check_code

def index(request):
    return render(request, 'base.html')


def image_code(request):
    '''生成验证码'''

    # 调用pillow函数，生成图片
    img, code_string = check_code()

    # 写入到自己的session中，以便后续获取验证码再进行校验
    request.session['image_code'] = code_string
    # 给Session设置一个60秒超时
    request.session.set_expiry(60)

    stream = BytesIO()
    img.save(stream, 'png')
    return HttpResponse(stream.getvalue())



class LoginForm(BootStrapForm):
    username = forms.CharField(
        label='用户名',
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=True,
    )
    password = forms.CharField(
        label='密码',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}, render_value=True),
        required=True,
    )
    code = forms.CharField(
        label='验证码',
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=True,
    )
    
    # 移除原有的clean_password等验证方法，仅保留验证码验证
    def clean_code(self):
        user_input_code = self.cleaned_data.get('code')
        image_code = self.request.session.get('image_code', '')
        if not image_code:
            raise forms.ValidationError("验证码已过期")
        if image_code.lower() != user_input_code.lower():
            raise forms.ValidationError("验证码错误")
        return user_input_code
   

def user_login(request):
    """使用Django内置认证系统的登录功能"""
    if request.method == 'GET':
        form = LoginForm()
        return render(request, 'login.html', {'form': form})
    
    form = LoginForm(request.POST)
    form.request = request  # 将request传递给表单，以便验证验证码
    
    if form.is_valid():
        # 验证成功，获取用户名和密码
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        
        # 使用Django内置认证函数验证用户
        user = authenticate(request, username=username, password=password)
        if not user:
            form.add_error('password', '用户名或密码错误')
            return render(request, 'login.html', {'form': form})
        
        # 登录用户并设置会话
        login(request, user)
        request.session.set_expiry(60*60*24*7)  # 7天过期
        
        # 登录成功后重定向
        return redirect("index")
    
    return render(request, 'login.html', {'form': form})

def user_logout(request):
    """用户登出"""
    logout(request)
    return redirect('login')

accounts/views/department.py
from django.shortcuts import render, redirect, HttpResponse

from accounts import models
from utils.user_decorator import admin_or_superuser_required, superuser_required


@admin_or_superuser_required
def department_list(request):
    if request.method == 'GET':
        # 部门列表
        queryset = models.Department.objects.all()
    return render(request, 'department_list.html', {'queryset': queryset})


@superuser_required
def department_add(request):
    '''添加部门'''
    if request.method == 'GET':
        return render(request, 'department_add.html')

    title = request.POST.get('title')
    models.Department.objects.create(title=title)
    return redirect('/accounts/department/list/')


@superuser_required
def department_delete(request):
    '''删除部门'''
    nid = request.GET.get('nid')
    models.Department.objects.filter(id=nid).delete()
    return redirect('/accounts/department/list/')


@superuser_required
def department_edit(request, nid):
    '''修改部门'''
    # 通过nid获取数据，获取到的是一个列表对象，获取第一个
    if request.method == 'GET':
        row_object = models.Department.objects.filter(id=nid).first()
        return render(request, 'department_edit.html', {'row_object': row_object})
    title = request.POST.get('title')
    models.Department.objects.filter(id=nid).update(title=title)
    return redirect('/accounts/department/list')


@superuser_required
def department_multi(request):
    '''批量上传 (excel)'''
    from openpyxl import load_workbook
    # django.core.files.uploadedfile.InMemoryUploadedFile

    # 1.获取用户上传的对象文件
    file_object = request.FILES.get("exc")
    # print(type(file_object))

    # 2.对象传递给openpyxl，由openpyxl读取文件的内容
    wb = load_workbook(file_object)
    sheet = wb.worksheets[0]

    # 3.循环获取每一行数据
    for row in sheet.iter_rows(min_row=2):
        text = row[0].value

        exists = models.Department.objects.filter(title=text).exists()
        if not exists:
            models.Department.objects.create(title=text)

    # with open(file_object.title, mode='wb') as f:
    #     for chunk in file_object:
    #         f.write(chunk)

    return redirect("/accounts/department/list/")

accounts/views/subject.py
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse

from accounts import models
from utils.bootstrap import BootStrapModelForm
from utils.pagination import Pagination
from utils.user_decorator import admin_or_superuser_required, superuser_required
# Create your views here.


class SubjectModelForm(BootStrapModelForm):
    class Meta:
        model = models.Subject
        fields = "__all__"


@admin_or_superuser_required
def subject_list(request):
    '''学科列表'''
    form = SubjectModelForm()
    # if request.method == 'GET':
    #     queryset = models.Subject.objects.all()
    queryset = models.Subject.objects.all()
    page_object = Pagination(request, queryset)

    contxt = {
        'form': form,
        'queryset': page_object.page_queryset,
        'page_string': page_object.html(),
    }
    return render(request, 'subject_list.html', contxt)


@csrf_exempt
@superuser_required
def subject_add(request):
    '''学科添加(Ajax请求)'''
    form = SubjectModelForm(request.POST)
    if form.is_valid():
        form.save()
        return JsonResponse({"status": True})
    return JsonResponse({'status': False, 'error': form.errors})


@superuser_required
def subject_delete(request):
    '''学科删除'''
    uid = request.GET.get('uid')
    exists = models.Subject.objects.filter(id=uid).exists()
    if not exists:
        return JsonResponse({'status': False, 'error': '删除失败，数据不存在'})
    models.Subject.objects.filter(id=uid).delete()
    return JsonResponse({'status': True})


def subject_detail(request):
    '''根据ID获取学科详情'''
    uid = request.GET.get('uid')
    row_dict = models.Subject.objects.filter(id=uid).values('title').first()
    if not row_dict:
        return JsonResponse({"status": False, 'error': "数据不存在"})
    result = {
        'status': True,
        'data': row_dict,
    }
    return JsonResponse(result)


@csrf_exempt
@superuser_required
def subject_edit(request):
    '''编辑学科'''
    uid = request.GET.get('uid')
    row_object = models.Subject.objects.filter(id=uid).first()
    if not row_object:
        return JsonResponse({"status": False, 'error': "数据不存在,请刷新重试"})

    form = SubjectModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return JsonResponse({"status": True})
    return JsonResponse({'status': False, 'error': form.errors})


@superuser_required
def subject_multi(request):
    '''批量上传 (excel)'''
    from openpyxl import load_workbook
    # django.core.files.uploadedfile.InMemoryUploadedFile

    # 1.获取用户上传的对象文件
    file_object = request.FILES.get("exc")
    # print(type(file_object))

    # 2.对象传递给openpyxl，由openpyxl读取文件的内容
    wb = load_workbook(file_object)
    sheet = wb.worksheets[0]

    # 3.循环获取每一行数据
    for row in sheet.iter_rows(min_row=2):
        text = row[0].value

        exists = models.Subject.objects.filter(title=text).exists()
        if not exists:
            models.Subject.objects.create(title=text)

    # with open(file_object.title, mode='wb') as f:
    #     for chunk in file_object:
    #         f.write(chunk)

    return redirect("/accounts/subject/list/")

accounts/templates/update_avatar.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  修改头像
{% endblock title %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">请在此处修改</h3>
        </div>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="card-body">
            <div class="form-group">
              <label for="id_avatar">当前头像</label>
              <div class="mb-3">
                {% if request.user.avatar %}
                  <img id="currentAvatar"
                       src="{{ request.user.avatar.url }}"
                       alt="当前头像"
                       class="img-circle img-thumbnail"
                       style="max-width: 200px">
                {% else %}
                  <img id="currentAvatar"
                       src="{% static 'img/default_avatar.jpg' %}"
                       alt="默认头像"
                       class="img-circle img-thumbnail"
                       style="max-width: 200px">
                {% endif %}
              </div>
            </div>
            <!-- 修改的表单字段 -->
            <div class="form-group">
              {{ form.avatar.label_tag }}
              {{ form.avatar }}
              <small class="form-text text-muted">{{ form.avatar.help_text }}</small>
              {% if form.avatar.errors %}<div class="alert alert-danger">{{ form.avatar.errors }}</div>{% endif %}
            </div>
            <!-- 新增头像预览区域 -->
            <div class="form-group">
              <label for="id_avatar">预览新头像</label>
              <div class="mb-3">
                <img id="previewAvatar"
                     src=""
                     alt="新头像预览"
                     class="img-circle img-thumbnail d-none"
                     style="max-width: 200px">
              </div>
            </div>
          </div>
          <div class="card-footer">
            <button type="submit" class="btn btn-primary">上传头像</button>
            <a href="{% url 'accounts:user_profile' %}" class="btn btn-default">取消</a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}
{% block js %}
  <script>
    // 头像预览功能
    document.addEventListener('DOMContentLoaded', function() {
      const fileInput = document.getElementById('id_avatar');
      const previewImg = document.getElementById('previewAvatar');
      
      fileInput.addEventListener('change', function(e) {
        const file = e.target.files[0];
        if (file) {
          // 检查文件类型是否为图片
          if (file.type.startsWith('image/')) {
            const reader = new FileReader();
            
            reader.onload = function(event) {
              previewImg.src = event.target.result;
              previewImg.classList.remove('d-none'); // 显示预览图
            };
            
            reader.readAsDataURL(file);
          } else {
            alert('请选择图片文件！');
            // 清空文件选择（可选）
            fileInput.value = '';
          }
        }
      });
    });
  </script>
{% endblock js %}

accounts/templates/user_edit_profile.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
  <!-- 添加Bootstrap Datepicker的CSS -->
  <link rel="stylesheet"
        href="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
{% endblock css %}
{% block title %}
  {{ page_title }}
{% endblock title %}
{% block content %}
  <div class="container-fluid">
    <div class="row">
      <!-- 左侧个人信息卡片 (与profile.html相同) -->
      <div class="col-md-3">
        <!-- 个人资料卡片 -->
        <div class="card card-primary card-outline">
          <div class="card-body box-profile">
            <!-- 头像 -->
            <div class="text-center">
              {% if user.avatar %}
                <img class="profile-user-img img-fluid img-circle"
                     src="{{ user.avatar.url }}"
                     alt="用户头像">
              {% else %}
                <img class="profile-user-img img-fluid img-circle"
                     src="{% static 'img/default_avatar.jpg' %}"
                     alt="默认头像">
              {% endif %}
            </div>
            <h3 class="profile-username text-center">{{ user.name }}</h3>
            <p class="text-muted text-center">{{ user.department|default:"未设置部门" }}</p>
            <hr>
            <!-- 个人信息列表 -->
            <ul class="list-group list-group-unbordered mb-3">
              <li class="list-group-item">
                <b>用户名</b>
                <a class="float-right">{{ user.username }}</a>
              </li>
              <li class="list-group-item">
                <b>注册时间</b>
                <a class="float-right">{{ user.date_joined|date:"Y-m-d H:i" }}</a>
              </li>
              <li class="list-group-item">
                <b>上次登录</b>
                <a class="float-right">
                  {% if user.last_login %}
                    {{ user.last_login }}
                  {% else %}
                    首次登录
                  {% endif %}
                </a>
              </li>
              {% comment %} <li class="list-group-item">
                <b>联系方式</b>
                <a class="float-right">{{ user.phone|default:"未设置" }}</a>
              </li> {% endcomment %}
            </ul>
          </div>
          {% if not is_other_user %}
            <div>
              <h4 class="mb-3">安全设置</h4>
              <div class="card">
                <div class="card-body">
                  <a href="{% url 'accounts:change_password' %}"
                     class="btn btn-warning btn-flat btn-block">
                    <i class="fa fa-key mr-2"></i>修改密码
                  </a>
                  <a href="{% url 'accounts:update_avatar' %}"
                     class="btn btn-info btn-flat btn-block">
                    <i class="fa fa-user-circle mr-2"></i>修改头像
                  </a>
                </div>
              </div>
            </div>
          {% endif %}
        </div>
      </div>
      <!-- 右侧编辑区域 -->
      <div class="col-md-9">
        <div class="card">
          <div class="card-header with-border">
            <h3 class="card-title">
              编辑个人资料
              <div class="pull-right">
                <a href="{% url 'accounts:user_profile' %}" class="btn btn-default">
                  <i class="fa fa-arrow-left"></i> 返回
                </a>
              </div>
            </h3>
          </div>
          <div class="card-body">
            <form method="post">
              {% csrf_token %}
              <div class="row">
                <div class="col-md-6">
                  <h4 class="mb-3">账户信息</h4>
                  <!-- 姓名 (只读) -->
                  <div class="form-group row">
                    <label class="col-sm-2 col-form-label">姓名</label>
                    <div class="col-sm-10">
                      <p class="form-control-static">{{ user.name }}</p>
                    </div>
                  </div>
                  <!-- 手机号 -->
                  <div class="form-group row">
                    <label class="col-sm-2 col-form-label">手机号</label>
                    <div class="col-sm-10">
                      {{ form.phone }}
                      {% if form.phone.errors %}
                        <div class="text-danger">
                          {% for error in form.phone.errors %}<small>{{ error }}</small>{% endfor %}
                        </div>
                      {% endif %}
                      <small class="form-text text-muted">手机号将作为登录用户名</small>
                    </div>
                  </div>
                  <!-- 邮箱 -->
                  <div class="form-group row">
                    <label class="col-sm-2 col-form-label">邮箱</label>
                    <div class="col-sm-10">
                      {{ form.email }}
                      {% if form.email.errors %}
                        <div class="text-danger">
                          {% for error in form.email.errors %}<small>{{ error }}</small>{% endfor %}
                        </div>
                      {% endif %}
                    </div>
                  </div>
                  <!-- 身份证号 -->
                  <div class="form-group row">
                    <label class="col-sm-2 col-form-label">身份证号</label>
                    <div class="col-sm-10">
                      {{ form.idnumber }}
                      {% if form.idnumber.errors %}
                        <div class="text-danger">
                          {% for error in form.idnumber.errors %}<small>{{ error }}</small>{% endfor %}
                        </div>
                      {% endif %}
                    </div>
                  </div>
                  <!-- 部门 -->
                  <div class="form-group row">
                    <label class="col-sm-2 col-form-label">部门</label>
                    <div class="col-sm-10">{{ form.department }}</div>
                  </div>
                  <!-- 学科 -->
                  <div class="form-group row">
                    <label class="col-sm-2 col-form-label">学科</label>
                    <div class="col-sm-10">{{ form.subject }}</div>
                  </div>
                  <!-- 性别 -->
                  <div class="form-group row">
                    <label class="col-sm-2 col-form-label">性别</label>
                    <div class="col-sm-10">
                      <div class="form-check form-check-inline">
                        <input class="form-check-input"
                               type="radio"
                               name="gender"
                               id="gender_male"
                               value="1"
                               {% if form.gender.value == 1 %}checked{% endif %}>
                        <label class="form-check-label" for="gender_male">男</label>
                      </div>
                      <div class="form-check form-check-inline">
                        <input class="form-check-input"
                               type="radio"
                               name="gender"
                               id="gender_female"
                               value="2"
                               {% if form.gender.value == 2 %}checked{% endif %}>
                        <label class="form-check-label" for="gender_female">女</label>
                      </div>
                      {% if form.gender.errors %}
                        <div class="text-danger">
                          {% for error in form.gender.errors %}<small>{{ error }}</small>{% endfor %}
                        </div>
                      {% endif %}
                    </div>
                  </div>
                  <h4>个人信息</h4>
                  <!-- 民族 -->
                  <div class="form-group row">
                    <label class="col-sm-2 col-form-label">民族</label>
                    <div class="col-sm-10">{{ form.nation }}</div>
                  </div>
                  <!-- 政治面貌 -->
                  <div class="form-group row">
                    <label class="col-sm-2 col-form-label">政治面貌</label>
                    <div class="col-sm-10">{{ form.political_status }}</div>
                  </div>
                  <!-- 籍贯 -->
                  <div class="form-group row">
                    <label class="col-sm-2 col-form-label">籍贯</label>
                    <div class="col-sm-10">{{ form.native_place }}</div>
                  </div>
                  <!-- 现住址 -->
                  <div class="form-group row">
                    <label class="col-sm-2 col-form-label">现住址</label>
                    <div class="col-sm-10">{{ form.address }}</div>
                  </div>
                  <!-- 出生日期 -->
                  <div class="form-group row">
                    <label class="col-sm-2 col-form-label">出生日期</label>
                    <div class="col-sm-5">
                      <input type="text"
                             class="form-control date-input"
                             id="id_birthday"
                             name="birthday"
                             value="{{ form.birthday.value|default:'' }}">
                    </div>
                  </div>
                  <!-- 以下是不允许编辑的字段 -->
                  <div class="form-group row">
                    <label class="col-sm-10 col-form-label">参加工作时间、职称时间等人社室更新</label>
                  </div>
                </div>
                <!-- 更多只读字段... -->
              </div>
              <!-- 学历信息部分 -->
              <div class="row mt-4">
                <div class="col-md-12">
                  <h4>学历信息</h4>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group row">
                    <label class="col-sm-2 col-form-label">第一学历</label>
                    <div class="col-sm-10">{{ form.first_education }}</div>
                  </div>
                  <div class="form-group row">
                    <label class="col-sm-2 col-form-label">毕业院校</label>
                    <div class="col-sm-10">{{ form.first_education_school }}</div>
                  </div>
                  <div class="form-group row">
                    <label class="col-sm-2 col-form-label">专业</label>
                    <div class="col-sm-10">{{ form.first_education_major }}</div>
                  </div>
                  <!-- 第一学历毕业时间 -->
                  <div class="form-group row">
                    <label class="col-sm-2 col-form-label">毕业时间</label>
                    <div class="col-sm-5">
                      <input type="text"
                             class="form-control date-input"
                             id="id_first_education_time"
                             name="first_education_time"
                             value="{{ form.first_education_time.value|default:'' }}">
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group row">
                    <label class="col-sm-2 col-form-label">最高学历</label>
                    <div class="col-sm-10">{{ form.highest_education }}</div>
                  </div>
                  <div class="form-group row">
                    <label class="col-sm-2 col-form-label">毕业院校</label>
                    <div class="col-sm-10">{{ form.highest_education_school }}</div>
                  </div>
                  <div class="form-group row">
                    <label class="col-sm-2 col-form-label">专业</label>
                    <div class="col-sm-10">{{ form.highest_education_major }}</div>
                  </div>
                  <!-- 最高学历毕业时间 -->
                  <div class="form-group row">
                    <label class="col-sm-2 col-form-label">毕业时间</label>
                    <div class="col-sm-5">
                      <input type="text"
                             class="form-control date-input"
                             id="id_highest_education_time"
                             name="highest_education_time"
                             value="{{ form.highest_education_time.value|default:'' }}">
                    </div>
                  </div>
                </div>
              </div>
              <div class="row mt-4">
                <div class="col-md-12">
                  <button type="submit" class="btn btn-primary">保存更改</button>
                  <a href="{% url 'accounts:user_profile' %}" class="btn btn-default ml-2">取消</a>
                </div>
              </div>
            </form>
            <!-- 补充了缺失的表单结束标签 -->
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}
{% block js %}
  <!-- 引入Bootstrap Datepicker及其中文语言包 -->
  <script src="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
  <script src="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/locales/bootstrap-datepicker.zh-CN.min.js' %}"
          charset="UTF-8"></script>
  <script>
$(function() {
  // 初始化日期选择器
  $('.date-input').datepicker({
    format: 'yyyy-mm-dd',       // 日期格式
    language: 'zh-CN',          // 中文语言
    autoclose: true,            // 选择日期后自动关闭
    todayHighlight: true,       // 高亮显示今天
    orientation: "top auto",  // 弹出位置
    //todayBtn: true,               // 显示"今天"按钮
    //clearBtn: true,               // 显示"清除"按钮
  });
  
  // 设置初始值
  {% if form.birthday.value %}
    $('#id_birthday').datepicker('update', '{{ form.birthday.value|date:"Y-m-d" }}');
  {% endif %}
  {% if form.first_education_time.value %}
    $('#id_first_education_time').datepicker('update', '{{ form.first_education_time.value|date:"Y-m-d" }}');
  {% endif %}
  {% if form.highest_education_time.value %}
    $('#id_highest_education_time').datepicker('update', '{{ form.highest_education_time.value|date:"Y-m-d" }}');
  {% endif %}
});
  </script>
{% endblock js %}