accounts/urls.py
from django.urls import path
from accounts.views import user, department, subject, user_profile

app_name = 'accounts'

urlpatterns = [
    # 用户管理
    path('user/list/', user.user_list, name='user_list'),
    path('user/add/', user.user_add, name='user_add'),
    path('user/delete/', user.user_delete, name='user_delete'),
    path('user/<int:nid>/edit/', user.user_edit, name='user_edit'),
    path('user/import/', user.import_users, name='import_users'),
    path('user/<int:nid>/reset/', user.user_reset, name='user_reset'),
    
    # 部门管理
    path('department/list/', department.department_list, name='department_list'),
    path('department/add/', department.department_add, name='department_add'),
    path('department/delete/', department.department_delete, name='department_delete'),
    path('department/<int:nid>/edit/', department.department_edit, name='department_edit'),
    path('department/multi/', department.department_multi, name='department_multi'),

    # 学科管理
    path('subject/list/', subject.subject_list, name='subject_list'),
    path('subject/add/', subject.subject_add, name='subject_add'),
    path('subject/delete/', subject.subject_delete, name='subject_delete'),
    path('subject/edit/', subject.subject_edit, name='subject_edit'),
    path('subject/detail/', subject.subject_detail, name='subject_detail'),
    path('subject/multi/', subject.subject_multi, name='subject_multi'), 
    
    # 个人用户
    path('profile/', user_profile.user_profile, name='user_profile'),
    path('change_password/', user_profile.change_password, name='change_password'),
    path('update_avatar/', user_profile.update_avatar, name='update_avatar'), 
    path('userprofile/edit/', user_profile.user_edit_profile, name='user_edit_profile'),

]

assessments/urls.py
from django.urls import path
from assessments.views import semester, assessdepart
from assessments.views import cultura_mid, cultura_end, cultura_term
from assessments.views import music_mid, music_end, music_term, art_mid, art_end, art_term
from assessments.views import pe_mid, pe_end, pe_term
from assessments.views import it_mid, it_end, it_term
from assessments.views import groupleader_mid, groupleader_end, groupleader_term
from assessments.views import headteacher_mid, headteacher_end, headteacher_term
from assessments.views import eduadmin, aladmin, deputy
from assessments.views import user_assess

app_name = 'assessments'

urlpatterns = [
    # 学年管理
    path('semester/list/', semester.semester_list, name='semester_list'),
    path('semester/add/', semester.semester_add, name='semester_add'),
    path('semester/delete/', semester.semester_delete, name='semester_delete'),
    path('semester/detail/', semester.semester_detail, name='semester_detail'),
    path('semester/edit/', semester.semester_edit, name='semester_edit'),
    
    # 考核部门管理
    path('assessdepart/list/', assessdepart.assessdepart_list, name='assessdepart_list'),
    path('assessdepart/add/', assessdepart.assessdepart_add, name='assessdepart_add'),
    path('assessdepart/delete/', assessdepart.assessdepart_delete, name='assessdepart_delete'),
    path('assessdepart/detail/', assessdepart.assessdepart_detail, name='assessdepart_detail'),
    path('assessdepart/edit/', assessdepart.assessdepart_edit, name='assessdepart_edit'),
    path('assessdepart/import/', assessdepart.assessdepart_import, name='assessdepart_import'),
    
    # 文化课教师期中考核管理
    path('teacher_autocomplete/', cultura_mid.teacher_autocomplete, name='teacher_autocomplete'),
    path('cultura/midlist/', cultura_mid.cultura_mid_list, name='cultura_mid_list'),
    path('cultura/midadd/', cultura_mid.cultura_mid_add, name='cultura_mid_add'),
    path('cultura/middelete/', cultura_mid.cultura_mid_delete, name='cultura_mid_delete'),
    path('cultura/midedit/<int:pk>', cultura_mid.cultura_mid_edit, name='cultura_mid_edit'),
    path('cultura/midimport/', cultura_mid.cultura_mid_import, name='cultura_mid_import'),
    path('cultura/mid/export/', cultura_mid.cultura_mid_export, name='cultura_mid_export'),
    path('cultura_mid/update_rank/', cultura_mid.cultura_mid_update_rank, name='cultura_mid_update_rank'),
    # 文化科期末考核管理
    path('cultura/endllist/', cultura_end.cultura_end_list, name='cultura_end_list'),
    path('cultura/endadd/', cultura_end.cultura_end_add, name='cultura_end_add'),
    path('cultura/enddelete/', cultura_end.cultura_end_delete, name='cultura_end_delete'),
    path('cultura/endedit/<int:pk>', cultura_end.cultura_end_edit, name='cultura_end_edit'),
    path('cultura/endimport/', cultura_end.cultura_end_import, name='cultura_end_import'),
    path('cultura_end/update_rank/', cultura_end.cultura_end_update_rank, name='cultura_end_update_rank'),
    path('cultura/end/export/', cultura_end.cultura_end_export, name='cultura_end_export'),   
    # 文化科教师学期考核管理
    path('cultura/termlist/', cultura_term.cultura_term_list, name='cultura_term_list'),
    path('cultura/termadd/', cultura_term.cultura_term_add, name='cultura_term_add'),
    path('cultura/termdelete/', cultura_term.cultura_term_delete, name='cultura_term_delete'),
    path('cultura/termedit/<int:pk>', cultura_term.cultura_term_edit, name='cultura_term_edit'),
    path('cultura/termimport/', cultura_term.cultura_term_import, name='cultura_term_import'),
    path('cultura_term/update_rank/', cultura_term.cultura_term_update_rank, name='cultura_term_update_rank'),
    path('cultura/term/export/', cultura_term.cultura_term_export, name='cultura_term_export'),
    
    # 音乐教师期中考核管理
    path('music/midlist/', music_mid.music_mid_list, name='music_mid_list'),
    path('music/midadd/', music_mid.music_mid_add, name='music_mid_add'),
    path('music/middelete/', music_mid.music_mid_delete, name='music_mid_delete'),
    path('music/midedit/<int:pk>',music_mid.music_mid_edit, name='music_mid_edit'),
    path('music/midimport/', music_mid.music_mid_import, name='music_mid_import'),
    path('music/mid/export/', music_mid.music_mid_export, name='music_mid_export'),
    path('music_mid/update_rank/', music_mid.music_mid_update_rank, name='music_mid_update_rank'),
    # 音乐期末考核管理
    path('music/endlist/', music_end.music_end_list, name='music_end_list'),
    path('music/endadd/', music_end.music_end_add, name='music_end_add'),
    path('music/enddelete/', music_end.music_end_delete, name='music_end_delete'),
    path('music/endedit/<int:pk>', music_end.music_end_edit, name='music_end_edit'),
    path('music/endimport/', music_end.music_end_import, name='music_end_import'),
    path('music/end/export/', music_end.music_end_export, name='music_end_export'),
    path('music_end/update_rank/', music_end.music_end_update_rank, name='music_end_update_rank'),
    # 音乐学期管理url
    path('music/termlist/', music_term.music_term_list, name='music_term_list'),
    path('music/termadd/', music_term.music_term_add, name='music_term_add'),
    path('music/termdelete/', music_term.music_term_delete, name='music_term_delete'),
    path('music/termedit/<int:pk>', music_term.music_term_edit, name='music_term_edit'),
    path('music/termimport/', music_term.music_term_import, name='music_term_import'),
    path('music/term/export/', music_term.music_term_export, name='music_term_export'),
    path('music_term/update_rank/', music_term.music_term_update_rank, name='music_term_update_rank'),
    
    # 美术教师期中考核管理
    path('art/midlist/', art_mid.art_mid_list, name='art_mid_list'),
    path('art/midadd/', art_mid.art_mid_add, name='art_mid_add'),
    path('art/middelete/', art_mid.art_mid_delete, name='art_mid_delete'),
    path('art/midedit/<int:pk>', art_mid.art_mid_edit, name='art_mid_edit'),
    path('art/midimport/', art_mid.art_mid_import, name='art_mid_import'),
    path('art/mid/export/', art_mid.art_mid_export, name='art_mid_export'),
    path('art_mid/update_rank/', art_mid.art_mid_update_rank, name='art_mid_update_rank'),
    # 美术期末考核管理
    path('art/endlist/', art_end.art_end_list, name='art_end_list'),
    path('art/endadd/', art_end.art_end_add, name='art_end_add'),
    path('art/enddelete/', art_end.art_end_delete, name='art_end_delete'),
    path('art/endedit/<int:pk>', art_end.art_end_edit, name='art_end_edit'),
    path('art/endimport/', art_end.art_end_import, name='art_end_import'),
    path('art/end/export/', art_end.art_end_export, name='art_end_export'),
    path('art_end/update_rank/', art_end.art_end_update_rank, name='art_end_update_rank'),
    # 美术学期管理url
    path('art/termlist/', art_term.art_term_list, name='art_term_list'),
    path('art/termadd/', art_term.art_term_add, name='art_term_add'),
    path('art/termdelete/', art_term.art_term_delete, name='art_term_delete'),
    path('art/termedit/<int:pk>', art_term.art_term_edit, name='art_term_edit'),
    path('art/termimport/', art_term.art_term_import, name='art_term_import'),
    path('art/term/export/', art_term.art_term_export, name='art_term_export'),
    path('art_term/update_rank/', art_term.art_term_update_rank, name='art_term_update_rank'),
    
    # 体育教师期中考核管理
    path('pe/midlist/', pe_mid.pe_mid_list, name='pe_mid_list'),
    path('pe/midadd/', pe_mid.pe_mid_add, name='pe_mid_add'),
    path('pe/middelete/', pe_mid.pe_mid_delete, name='pe_mid_delete'),
    path('pe/midedit/<int:pk>', pe_mid.pe_mid_edit, name='pe_mid_edit'),
    path('pe/midimport/', pe_mid.pe_mid_import, name='pe_mid_import'),
    path('pe/mid/export/', pe_mid.pe_mid_export, name='pe_mid_export'),
    path('pe_mid/update_rank/', pe_mid.pe_mid_update_rank, name='pe_mid_update_rank'),
    # 体育期末考核管理
    path('pe/endlist/', pe_end.pe_end_list, name='pe_end_list'),
    path('pe/endadd/', pe_end.pe_end_add, name='pe_end_add'),
    path('pe/enddelete/', pe_end.pe_end_delete, name='pe_end_delete'),
    path('pe/endedit/<int:pk>', pe_end.pe_end_edit, name='pe_end_edit'),
    path('pe/endimport/', pe_end.pe_end_import, name='pe_end_import'),
    path('pe/end/export/', pe_end.pe_end_export, name='pe_end_export'),
    path('pe_end/update_rank/', pe_end.pe_end_update_rank, name='pe_end_update_rank'),
    # 体育学期管理
    path('pe/termlist/', pe_term.pe_term_list, name='pe_term_list'),
    path('pe/termadd/', pe_term.pe_term_add, name='pe_term_add'),
    path('pe/termdelete/', pe_term.pe_term_delete, name='pe_term_delete'),
    path('pe/termedit/<int:pk>', pe_term.pe_term_edit, name='pe_term_edit'),
    path('pe/termimport/', pe_term.pe_term_import, name='pe_term_import'),
    path('pe/term/export/', pe_term.pe_term_export, name='pe_term_export'),
    path('pe_term/update_rank/', pe_term.pe_term_update_rank, name='pe_term_update_rank'),
    
    # 信息技术教师期中考核管理
    path('it/midlist/', it_mid.it_mid_list, name='it_mid_list'),
    path('it/midadd/', it_mid.it_mid_add, name='it_mid_add'),
    path('it/middelete/', it_mid.it_mid_delete, name='it_mid_delete'),
    path('it/midedit/<int:pk>', it_mid.it_mid_edit, name='it_mid_edit'),
    path('it/midimport/', it_mid.it_mid_import, name='it_mid_import'),
    path('it/mid/export/', it_mid.it_mid_export, name='it_mid_export'),
    path('it_mid/update_rank/', it_mid.it_mid_update_rank, name='it_mid_update_rank'),
    # 信息技术期末考核管理
    path('it/endlist/', it_end.it_end_list, name='it_end_list'),
    path('it/endadd/', it_end.it_end_add, name='it_end_add'),
    path('it/enddelete/', it_end.it_end_delete, name='it_end_delete'),
    path('it/endedit/<int:pk>', it_end.it_end_edit, name='it_end_edit'),
    path('it/endimport/', it_end.it_end_import, name='it_end_import'),
    path('it/end/export/', it_end.it_end_export, name='it_end_export'),
    path('it_end/update_rank/', it_end.it_end_update_rank, name='it_end_update_rank'),
    # 信息技术学期管理
    path('it/termlist/', it_term.it_term_list, name='it_term_list'),

teacher_system/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import account
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # 首页
    path('', account.index, name='index'),
    
    # 后台管理
    path('admin/', admin.site.urls),
    
    # 登录注销
    path('image/code/', account.image_code, name='image_code'),
    path("login/", account.user_login, name="login"),
    path("logout/", account.user_logout, name="logout"),
    
    # 路由分发
    path('accounts/', include('accounts.urls')),
    path('assessments/', include('assessments.urls')),
    path('certificate/', include('certificate.urls')),
    
]

# 仅在开发环境中添加此配置,生产环境由Nginx处理
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

assessments/forms.py
# forms.py
from django import forms
from django.core.validators import FileExtensionValidator

# forms.py
class BatchImportForm(forms.Form):
    excel_file = forms.FileField(
        label="上传 Excel 文件",
        validators=[FileExtensionValidator(allowed_extensions=['xlsx'])],
    )

assessments/views/assessdepart.py
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from openpyxl import load_workbook

from assessments.models import AssessDepart
from utils.bootstrap import BootStrapModelForm
from utils.pagination import Pagination
from utils.user_decorator import superuser_required, admin_or_superuser_required

# Create your views here.


class AssessDepartModelForm(BootStrapModelForm):
    class Meta:
        model = AssessDepart
        fields = '__all__'


@admin_or_superuser_required
def assessdepart_list(request):
    '''考核部门列表'''
    form = AssessDepartModelForm()
    query = AssessDepart.objects.all()
    page_object = Pagination(request, query)
    context = {
        'form': form,
        'page_string': page_object.html(),
        'queryset': page_object.page_queryset,
    }
    return render(request, 'assessdepart_list.html', context)



@csrf_exempt
@superuser_required
def  assessdepart_add(request):
    '''考核部门添加(Ajax请求)'''
    form = AssessDepartModelForm(request.POST)
    if form.is_valid():
        form.save()
        return JsonResponse({"status": True})
    return JsonResponse({'status': False, 'error': form.errors})


@superuser_required
def assessdepart_delete(request):
    '''考核部门删除'''
    uid = request.GET.get('uid')
    exists = AssessDepart.objects.filter(id=uid).exists()
    if not exists:
        return JsonResponse({'status': False, 'error': '删除失败，数据不存在'})
    AssessDepart.objects.filter(id=uid).delete()
    return JsonResponse({'status': True})


def assessdepart_detail(request):
    '''根据ID获取考核部门详情'''
    uid = request.GET.get('uid')
    # row_dict = models.assessdepart.objects.filter(id=uid).values('title').first()
    row_dict = AssessDepart.objects.filter(id=uid).values('name').first()
    if not row_dict:
        return JsonResponse({"status":False, 'error':"数据不存在"})
    result = {
        'status': True,
        'data': row_dict,
    }
    return JsonResponse(result)
    
@csrf_exempt
@superuser_required
def assessdepart_edit(request):
    '''编辑考核部门'''
    uid = request.GET.get('uid')
    row_object = AssessDepart.objects.filter(id=uid).first()
    if not row_object:
        return JsonResponse({"status":False, 'error':"数据不存在,请刷新重试"})

    form = AssessDepartModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return JsonResponse({"status": True})
    return JsonResponse({'status': False, 'error': form.errors})


@superuser_required
def assessdepart_import(request):
    '''Excel表格批量导入考核部门'''
    # django.core.files.uploadedfile.InMemoryUploadedFile

    # 1.获取用户上传的对象文件
    file_object = request.FILES.get("exc")
    # print(type(file_object))

    # 2.对象传递给openpyxl，由openpyxl读取文件的内容
    wb = load_workbook(file_object)
    sheet = wb.worksheets[0]

    # 3.循环获取每一行数据
    for row in sheet.iter_rows(min_row=2):
        text = row[0].value

        exists = AssessDepart.objects.filter(name=text).exists()
        if not exists:
            AssessDepart.objects.create(name=text)

    # with open(file_object.title, mode='wb') as f:
    #     for chunk in file_object:
    #         f.write(chunk)
    return redirect("assessments:assessdepart_list")

assessments/templates/art_end_list.html
{% extends "base.html" %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'css/custom_table.css' %}">
{% endblock css %}
{% block title %}
  期末 美术教师综合管理考核成绩
{% endblock title %}
{% block title_d %}
  全部列表
{% endblock title_d %}
{% block content %}
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <div style="margin-bottom: 10px" class="clearfix">
            {% if request.user.is_superuser %}
              <a class="btn btn-success" href="{% url 'assessments:art_end_add' %}">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                新建考核
              </a>
            {% endif %}
            <!-- 多条件筛选表单 -->
            <div style="float: right; width: 100%; margin-top: 10px;">
              <form method="get" class="form-inline">
                <!-- 学期筛选 -->
                <div class="form-group">
                  <label for="semester">学期：</label>
                  <select name="semester" id="semester" class="form-control">
                    <option value="all">全部学期</option>
                    {% for semester in semesters %}
                      <option value="{{ semester.id }}"
                              {% if selected_semester == semester.id|stringformat:"s" %}selected{% endif %}>
                        {{ semester }}
                      </option>
                    {% endfor %}
                  </select>
                </div>
                <!-- 考核类型筛选 -->
                <div class="form-group" style="margin-left: 10px;">
                  <label for="term_type">考核类型：</label>
                  <select name="term_type" id="term_type" class="form-control">
                    <option value="all">全部类型</option>
                    {% for term_type in term_types %}
                      <option value="{{ term_type.id }}"
                              {% if selected_term_type == term_type.id|stringformat:"s" %}selected{% endif %}>
                        {{ term_type.name }}
                      </option>
                    {% endfor %}
                  </select>
                </div>
                <!-- 考核部门筛选 -->
                <div class="form-group" style="margin-left: 10px;">
                  <label for="assess_depart">考核部门：</label>
                  <select name="assess_depart" id="assess_depart" class="form-control">
                    <option value="all">全部部门</option>
                    {% for depart in assess_departs %}
                      <option value="{{ depart.id }}"
                              {% if selected_assess_depart == depart.id|stringformat:"s" %}selected{% endif %}>
                        {{ depart.name }}
                      </option>
                    {% endfor %}
                  </select>
                </div>
                <!-- 学科筛选 -->
                <!-- 学科筛选 - 修正版 -->
                <div class="form-group">
                  <label for="subject">学科：</label>
                  <select name="subject" id="subject" class="form-control">
                    <option value="all">全部学科</option>
                    {% for subject in subjects %}
                      <option value="{{ subject.id }}"
                              {% if selected_subject|add:"0" == subject.id %}selected{% endif %}>
                        {{ subject.title }}
                      </option>
                    {% endfor %}
                  </select>
                </div>
                <!-- 教师姓名搜索 -->
                <div class="form-group" style="margin-left: 10px;">
                  <label for="teacher_name">教师姓名：</label>
                  <input type="text"
                         name="teacher_name"
                         id="teacher_name"
                         class="form-control"
                         value="{{ teacher_name }}"
                         placeholder="输入教师姓名">
                </div>
                <button type="submit" class="btn btn-primary" style="margin-left: 10px;">
                  <span class="glyphicon glyphicon-search"></span> 查询
                </button>
                <a href="?" class="btn btn-default" style="margin-left: 5px;">重置</a>
                <!-- 新增导出按钮 -->
                {% if request.user.is_superuser %}
                  <a href="{% url 'assessments:art_end_export' %}{% if request.GET.urlencode %}?{{ request.GET.urlencode }}{% endif %}"
                     class="btn btn-success"
                     style="margin-left: 5px">
                    <span class="glyphicon glyphicon-export"></span> 导出Excel
                  </a>
                {% endif %}
              </form>
            </div>
            <!-- /多条件筛选表单 -->
          </div>
          <div class="box-body">
            <div id="example2_wrapper"
                 class="dataTables_wrapper form-inline dt-bootstrap">
              <div class="row">
                <div class="col-sm-6"></div>
                <div class="col-sm-6"></div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <!-- Table -->
                  <table id="example2"
                         class="table table-bordered table-hover dataTable"
                         role="grid"
                         aria-describedby="example2_info">
                    <thead>
                      <tr role="row">
                        <th>ID</th>
                        <th>学期</th>
                        <th>考核类型</th>
                        <th>考核时间</th>
                        <th>考核部门</th>
                        <th>姓名</th>
                        <th>学科</th>
                        <th>考勤得分</th>
                        <th>课堂教学节数</th>
                        <th>专业课节数折算</th>
                        <th>艺体活动与竞赛培训节数折算</th>
                        <th>额外工作节数折算</th>
                        <th>总工作量节数</th>
                        <th>课时工作量成绩</th>
                        <th>监考得分</th>
                        <th>下学期艺考赋分</th>
                        <th>常规教学薄成绩</th>
                        <th>总成绩</th>
                        <th>名次</th>
                        <th>备注</th>
                        <th>公示完成</th>
                        {% if request.user.is_superuser %}<th>操作</th>{% endif %}
                      </tr>
                    </thead>
                    <tbody>
                      {% for obj in queryset %}
                        <tr role="row">
                          <th scope="row">{{ obj.id }}</th>
                          <td>{{ obj.semester }}</td>
                          <td>{{ obj.term_type }}</td>
                          <td>{{ obj.assess_time }}</td>
                          <td>{{ obj.assess_depart }}</td>
                          <td>{{ obj.teacher.name }}</td>
                          <td>{{ obj.teacher.subject }}</td>
                          <td>{{ obj.attend_score }}</td>
                          <td>{{ obj.class_hours }}</td>
                          <td>{{ obj.major_hours }}</td>
                          <td>{{ obj.activity_hours }}</td>
                          <td>{{ obj.extra_work_hours }}</td>
                          <td>{{ obj.total_workload }}</td>
                          <td>{{ obj.workload_score }}</td>
                          <td>{{ obj.invigilation_score }}</td>
                          <td>{{ obj.art_score }}</td>
                          <td>{{ obj.teach_book }}</td>
                          <td>{{ obj.total_score }}</td>
                          <td>{{ obj.rank | default:"" }}</td>
                          <td>{{ obj.remark }}</td>
                          <td>{{ obj.is_published|yesno:"是,否" }}</td>
                          {% if request.user.is_superuser %}
                            <td>
                              <a class="btn  btn-primary btn-xs"
                                 href="{% url 'assessments:art_end_edit' obj.id %}">编辑</a>
                              <a class="btn btn-danger btn-xs"
                                 href="javascript:void(0);"
                                 onclick="deleteItem('{{ obj.id }}', this);">删除</a>
                            </td>
                          {% endif %}
                        </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                  <!--End Table -->
                </div>
              </div>
              <div class="row">
                <div class="col-sm-5">
                  <div class="dataTables_info"
                       id="example2_info"
                       role="status"
                       aria-live="polite">
                    <a href="{% url 'assessments:my_assessments' %}"
                       class="btn btn-secondary mb-3">&larr; 返回个人考核列表</a> 每页展示20条数据
                  </div>
                </div>
                <div class="col-sm-7">
                  <div class="dataTables_paginate paging_simple_numbers"
                       id="example2_paginate">
                    <ul class="pagination">
                      {{ page_string }}
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% if request.user.is_superuser %}
          <div class="box">
            <div class="panel panel-default">
              <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                批量上传教师考核数据
              </div>
              <div class="panel-body">
                <form method="post"
                      enctype="multipart/form-data"
                      action="{% url 'assessments:art_end_import' %}">
                  {% csrf_token %}
                  <div class="form-group">
                    <label>选择考核文件Excel文件:</label>
                    <input type="file" name="excel_file" required>
                  </div>
                  <button type="submit" class="btn btn-primary">导入</button>
                </form>
                {% if messages %}
                  <div class="mt-3">
                    {% for message in messages %}
                      <div class="alert alert-{% if message.tags == 'success' %}success{% else %}danger{% endif %}">{{ message }}</div>
                    {% endfor %}
                  </div>
                {% endif %}
              </div>
            </div>
          </div>
          <div class="box">
            <div class="panel panel-default">
              <div class="panel-heading">
                <span class="glyphicon glyphicon-sort-by-attributes" aria-hidden="true"></span>
                更新教师考核名次及公示状态
              </div>
              <div class="panel-body">
                <form method="post"
                      enctype="multipart/form-data"
                      action="{% url 'assessments:art_end_update_rank' %}">
                  {% csrf_token %}
                  <div class="form-group">
                    <label>选择名次更新文件：</label>
                    <input type="file" name="excel_file" required>
                  </div>
                  <button type="submit" class="btn btn-success">
                    <span class="glyphicon glyphicon-upload"></span> 更新名次
                  </button>
                </form>
                {% if messages %}
                  <div class="mt-3">
                    {% for message in messages %}
                      <div class="alert alert-{% if message.tags == 'success' %}success{% elif message.tags == 'warning' %}warning{% else %}danger{% endif %}">
                        {{ message }}
                      </div>
                    {% endfor %}
                  </div>
                {% endif %}
              </div>
            </div>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock content %}
{% block js %}
  <script>
    function deleteItem(id, element) {
      if (confirm("确定要删除此用户吗？此操作不可撤销。")) {
        // 构建删除URL
        const deleteUrl = `/assessments/art/enddelete/?nid=${id}`;

        // 创建临时表单用于提交删除请求（防止URL参数被篡改）
        const form = document.createElement('form');
        form.method = 'POST';
        form.action = deleteUrl;

        // 添加CSRF令牌（Django需要CSRF保护）
        const csrfToken = document.querySelector('input[name="csrfmiddlewaretoken"]');
        if (csrfToken) {
          const csrfInput = document.createElement('input');
          csrfInput.type = 'hidden';
          csrfInput.name = 'csrfmiddlewaretoken';
          csrfInput.value = csrfToken.value;
          form.appendChild(csrfInput);
        }

        document.body.appendChild(form);
        form.submit();
      }
    }
  </script>
{% endblock js %}